initial_joint_positions:
  joint_map:
    torso_lift_joint: "0.15" 
    gripper_right_finger_joint: "0.004"
    gripper_finger_joint: "0.004"
    arm_1_joint : "0.2"
    arm_2_joint : "-1.34"
    arm_3_joint : "-0.2"
    arm_4_joint : "1.94"
    arm_5_joint : "-1.57"
    arm_6_joint : "1.37"
    arm_7_joint : "0"
    head_2_joint: "-0.97"
    
